### Site metadata ###

title: Cova Frontend Docs
description: "Base for a static website blog - built with Jekyll and the default theme"

### Build settings ###

url: https://danielr-iqmetrix.github.io
baseurl: /cova-frontend-docs

permalink: pretty

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  tools:
    output: true
  languages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - vendor/
  - 
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md
  - sample*.png

liquid:
  error_mode: strict

strict_front_matter: true
